### PR TITLE
Fix for the "permission denied" issue when using the install instructions in README.md

### PR DESCRIPTION
**Pull request by daryllreillo**

### CODE REVIEW

**Comment by daryllreillo** [comment]
I'm getting this error when using the install command:
**git@github.com: Permission denied (publickey).**

It worked when I replaced "git@github.com:angular/codelabs.git" to "https://github.com/angular/codelabs.git" in the command

**Comment by daryllreillo** [comment]
I meant for the cloning instructions using git in VSCode
I'm using VSCode v1.83.1 to execute the cloning commands

**Review by daryllreillo — COMMENTED** [review]
updated with CLA

**Comment by Muhammed-Ibrahem** [comment]
> I'm getting this error when using the install command: **[git@github.com](mailto:git@github.com): Permission denied (publickey).**
> 
> It worked when I replaced "[git@github.com](mailto:git@github.com):angular/codelabs.git" to "https://github.com/angular/codelabs.git" in the command

you get this issue because you don't have an ssh key on your account
you could generate an ssh key then add it to your account, after that if you tried to clone the repo again 
it will be cloned successfully.

the method you used worked for you, because you used another method which is HTTP
so both are working fine, depending on your authentication's info

**Comment by MarkTechson** [comment]
> > I'm getting this error when using the install command: **[git@github.com](mailto:git@github.com): Permission denied (publickey).**
> > It worked when I replaced "[git@github.com](mailto:git@github.com):angular/codelabs.git" to "https://github.com/angular/codelabs.git" in the command
> 
> you get this issue because you don't have an ssh key on your account you could generate an ssh key then add it to your account, after that if you tried to clone the repo again it will be cloned successfully.
> 
> the method you used worked for you, because you used another method which is HTTP so both are working fine, depending on your authentication's info

Yeah, @Muhammed-Ibrahem is right here. Thanks for this suggestion and taking the time to open the PR.

**Pull request closed without merging**
